name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Check format
        run: gofmt -s -d .
      - name: "B̜̻̟͍͕̘̭̟̑̀̉̀̂̓̃͢u̵̥͚̫̬̻̹̺̻̘̍̍͆͆̓̇͞͡ḯ̖̗̖̰̮̮̗̜̇̃̾̐͜l̨̟̫̥̬͔̝̭̖̣̅̆͋͂̔̎̚͜͝d̶̡̨̨͓͔̖̼͍̎̊̿̑̊̿̐͢"
        run: go build -v ./...
      - name: "Ţ̟͍̙͕̦̺̒̇̅̉̋̍́͊̎e̷̡͔̹̦̓͂̈̓̒͂͂̃͊͝ş̶̸͕͎̭̳̖̙̩̃͌͌̾̑͝͞t̛͕͕͖̭̰̥̻̫̯̒͊̆͜͟"
        run: go test -v ./...
